version: '3.8'

services:
  postgres:
    # Use postegres's official image from docker hub
    image: postgres:latest
    # Container name
    container_name: postgres_db
    # DB init
    env_file:
      - .env
    # ports exposed
    expose:
      - 6009
    ports:
      # maps port 5432 of the PostgreSQL container to port 5432 of your host machine.
      - '6009:5432'
    # Volumes
    # volumes:
    #   # Creates a persistent volume by linking your host machine's ./data directory to the container's /var/lib/postgresql/data directory, which ensures that the database data is persistent even if the container is shut down.
    #   - ./data:/var/lib/postgresql/data

  # this service is for GUI pgadmin4
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres