version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      # plugin pour voir ce qu'il se passe !!
      # credentials : guest guest
      - 15672:15672
    restart: unless-stopped